server:
  #  softNofileLimit: 1000
  #  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8082

logging:
  level: INFO
  loggers:
    com.javaeeeee: DEBUG

xmemeUrl : "xmeme.png"

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/memes?autoReconnect=true&useSSL=false
  user: root
  password: ashutosh
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true